---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: master
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: end-of-file-fixer
            exclude: 'states/macos/iterm2/com.googlecode.iterm2.plist'
          - id: pretty-format-json
            args: ['--autofix']
          - id: sort-simple-yaml
          - id: trailing-whitespace
            exclude: 'states/macos/iterm2/com.googlecode.iterm2.plist'
    - repo: https://github.com/thlorenz/doctoc
      rev: v1.3.1
      hooks:
          - id: doctoc
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.11.1
      hooks:
          - id: yamllint
